### ISSUE TITLE
Build error " cannot find ../ExtMem_Boot/Binary/NEON_BOOT.bin".

### ISSUE THREAD

**Issue by anand-010** [Zer0G/STM32F7508_Template#1]
Hello i am a beginner in lvgl and embedded development.
i've tried to run the template but i couldn't build it.
arm-none-eabi-gcc "../Core/Src/system_stm32f7xx.c" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F750xx -c -I../USB_HOST/App -I../USB_HOST/Target -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/ST/STM32_USB_Host_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Inc -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/CMSIS/Include -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Gfx/ui" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Gfx" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Drivers/BSP/STM32F7508-Discovery" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Drivers/BSP/Components/rk043fn48h" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Gfx/hal_stm_lvgl/tft" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Gfx/lvgl/src" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Gfx/lvgl/src/hal" -I"D:/lvgl_stm/STM32F7508_Template/STM32F7508Template/Gfx/hal_stm_lvgl/touchpad" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32f7xx.d" -MT"Core/Src/system_stm32f7xx.o" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "Core/Src/system_stm32f7xx.o"
arm-none-eabi-gcc -o "STM32F7508Template.elf" @"objects.list"   -mcpu=cortex-m7 -T"D:\lvgl_stm\STM32F7508_Template\STM32F7508Template\STM32F750N8HX_FLASH.ld" --specs=nosys.specs -Wl,-Map="STM32F7508Template.map" -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: cannot find ../ExtMem_Boot/Binary/NEON_BOOT.bin
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: cannot find ../ExtMem_Boot/Binary/NEON_BOOT.bin
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:119: STM32F7508Template.elf] Error 1
"make -j6 all" terminated with exit code 2. Build might be incomplete.

**Comment by anand-010** [comment]
I've changed the boot loader in the flsh ld file.
INPUT (../ExtMem_Boot/Binary/Bootloader.bin) /* bootloader bin file path (relative to the output folder)*/

But now got errors like
```
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: ./Core/Src/main.o: in function `main':
main.c:(.text.startup.main+0xbdc): undefined reference to `lv_init'
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: main.c:(.text.startup.main+0xbe0): undefined reference to `tft_init'
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: main.c:(.text.startup.main+0xbe4): undefined reference to `touchpad_init'
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: main.c:(.text.startup.main+0xbe8): undefined reference to `ui_init'
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: main.c:(.text.startup.main+0xbf0): undefined reference to `lv_timer_handler'
c:\st\stm32cubeide_1.10.1\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: ./Core/Src/stm32f7xx_it.o: in function `SysTick_Handler':
stm32f7xx_it.c:(.text.SysTick_Handler+0xa): undefined reference to `lv_tick_inc'
```

**Comment by anand-010** [comment]
I've included lvgl.h to the main but still got the same error.
i can find the it included in the compiler properties.
![image](https://user-images.githubusercontent.com/32414977/232289274-f1dd7403-9fff-41c3-9344-9f7c2202de8c.png)

**Comment by mataide** [comment]
@anand-010 did you manage to make it work?

**Comment by anand-010** [comment]
Yes some how  I've fixed it don't remember what are the things ive done.this device is verry slow for lvgl transitions so i stopped it.

**Comment by Zer0G** [comment]
I'll take back the project during the weekend to check it again.


*Giovanni Gherardi*
MSc Electronic Engineering, Firenze.



Via Stelvio 29, 41122 Modena, Italy

Via Molino 35, 50060 Pelago (FI), Italy

Tel: +39 328 5625298
email: ***@***.***



Il giorno ven 19 apr 2024 alle ore 04:42 Marcus Ataide <
***@***.***> ha scritto:
